### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by SteeveGL** [microsoft/artifacts-keyring#10]
How to build a docker image that require an Azure private feed?

**Comment by djpugh** [comment]
The method `creds = keyring.get_credential(index_url, None)` seems to create a username/token combo that works on that feed, so if you are building on e.g. a windows laptop where you are using artifacts-keyring, then that can give you a token to pass into your docker build, but if you are e.g. building on a non-interactive machine (apart from azure devops pipeline build agents with the PipAuthenticateTask), I think you'll need to create a PAT in devops directly and use that as an environment variable into the build - see #8

**Comment by drcrook1** [comment]
expanding on this, my docker containers are built on an ephemeral build server in a server pool.  Is it possible to just generate a token with this thing like we used to?

**Comment by johnterickson** [comment]
Using secrets in Docker is ... tricky. You'll need to do something analogous to this: https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md

**Comment by johnterickson** [comment]
The above link is really the master cookbook.  For some context, this tool is just a wrapper around https://github.com/microsoft/artifacts-credprovider so you can pass it the secret via VSS_NUGET_EXTERNAL_FEED_ENDPOINTS (yes it says NuGet, but don't worry about that 😊 ) see https://github.com/microsoft/artifacts-credprovider#environment-variables

You may also be interested in NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED

Some more info on tokens:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken
