### ISSUE TITLE
Python package includes tests

### ISSUE THREAD

**Issue by bancek** [microsoft/artifacts-keyring#16]
`setup.py` packages everything in `src` directory which includes `tests` directory. `tests` is now polluting PYTHONPATH.

Example:

```
$ python3.7 -m venv env
$ . env/bin/activate
$ ls env/lib/python3.7/site-packages/tests
ls: env/lib/python3.7/site-packages/tests: No such file or directory
$ pip install artifacts-keyring
$ ls env/lib/python3.7/site-packages/tests
__init__.py     __pycache__     test_backend.py
```

**Comment by omokoh** [comment]
Hey,
What is the impact of this issue?
Can you share more detail on the issue you are having?

**Comment by bancek** [comment]
It is causing issues with certain project folder structures.

Example:

```
PROJECT ROOT
- src
--- services
- tests
--- e2e
----- tests
------- services
```

If you add `tests/e2e` to `PYTHONPATH` it might clash with `tests` with from `artifacts-keyring` (depends if you append or prepend it) and besides it's really bad to pollute `PYTHONPATH` with random packages.
