### ISSUE TITLE
No usable version of the libssl was found and Unable to Authenticate

### ISSUE THREAD

**Issue by aloosley** [microsoft/artifacts-keyring#20]
Hello.

I am trying to upload / install python packages from my local machine to an Artifacts feed.

I have followed the twine / artifacts-keyring instructions on Azure Devops.  

When I go to upload my package
```
twine upload -r [hidden pypi name] dist/*
```

I always get the warning:
```
No usable version of the libssl was found
/home/---/anaconda3/envs/---/lib/python3.7/site-packages/twine/auth.py:61: UserWarning: Failed to get credentials: process with PID 20951 exited with code -6; additional error message: 
```

Then when I try to use my username and password credentials, they do not work.

I am running these packages with python 3.7.7 on pop_os! 19.10.

Thanks in advance.

**Comment by temporaer** [comment]
I have the same issue on Ubuntu 19.04, python 3.7.7. Digging slightly deeper, the message comes from 

```
/home/USER/miniconda3/envs/ptaml/lib/python3.7/site-packages/dotnetcore2/bin/dotnet \
exec /home/USER/miniconda3/envs/ptaml/lib/python3.7/
site-packages/artifacts_keyring/plugins/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll \
-Uri https://DEVOPS/_packaging/FEED/pypi/simple/ -IsRetry False -NonInteractive False -CanShowDialog False -OutputFormat Json
```

**Comment by bpeake-illuscio** [comment]
Same issue here using wsl2 on windows 10 running Ubuntu 20.04

**Comment by plang85** [comment]
seems broken on recent ubuntu versions

**Comment by AkhilGNair** [comment]
Is there any ETA on a fix for this 🙏 (Ubuntu 20.04)?

I also can't tell don't know if this repo is maintained or not, which makes it difficult to know if I should invest time into coming up with/implementing a workaround.

**Comment by aasim** [comment]
@temporaer @AkhilGNair The new version with the fix has been published, please try it from here and let us know if this works:
https://pypi.org/project/artifacts-keyring/0.2.10/

**Comment by temporaer** [comment]
@aasim @AkhilGNair the published fix requires you to manually install dotnet3 before attempting authentication, i'm not sure if the docs reflect that (yet).

**Comment by plang85** [comment]
Thanks for looking into this, unfortunately this is still broken for me. Tried on Ubuntu 20.04 and similar issues (WARNING: Keyring is skipped due to an exception: Failed to get credentials: process with PID 19068 exited with code 2). Also the plugin dependes on dotnetcore2 and has a warning for later versions @temporaer @aasim
