### ISSUE TITLE
Mac Big Sur is not supported

### ISSUE THREAD

**Issue by haojianzong** [microsoft/artifacts-keyring#29]
Hi,

This tool depends on dotnetcore2, which distributes binary blob that does not support the new Mac OS 11.0 beta.

https://pypi.org/simple/dotnetcore2/

So installing this tool on a new Mac OS will result in `No matching distribution found for dotnetcore2`

```
Collecting keyring==19.2.0
  Using cached keyring-19.2.0-py2.py3-none-any.whl (34 kB)
Collecting artifacts-keyring==0.2.8rc0
  Using cached artifacts_keyring-0.2.8rc0-py2.py3-none-any.whl (4.0 MB)
Collecting entrypoints
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting requests>=2.20.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
ERROR: Could not find a version that satisfies the requirement dotnetcore2; sys_platform != "win32" (from artifacts-keyring==0.2.8rc0) (from versions: none)
ERROR: No matching distribution found for dotnetcore2; sys_platform != "win32" (from artifacts-keyring==0.2.8rc0)
```

Since our development tool depends on artifacts-keyring, we will no longer be able to use future MacOS betas early.

Any idea or plan for this?

**Comment by aaroncrespo** [comment]
This also blocks bootstrapping our project under Big Sur.

**Comment by aaroncrespo** [comment]
There is a workaround posted elsewhere to downgrade pip to 19.3.1 however that workaround does not where on any system I've tried it on.

**Comment by zooba** [comment]
The eventual workaround will be to upgrade to a new version of pip that supports Big Sur. Right now, I don't believe any has been released, but keep an eye on pip updates.
