### ISSUE TITLE
artifacts-keyring not working with '--extra-index-url' in requirements.txt

### ISSUE THREAD

**Issue by niander** [microsoft/artifacts-keyring#30]
Issue seems to be related to this bug in pip: https://github.com/pypa/pip/issues/8103#issue-603840656
While that bug seems to have been fixed, whatever changed made there did not fix the problem with `artifacts-keyring`

If `--extra-index-url` is only in the requirements.txt `artifacts-keyring` won't try to get the credential. But if I include it in the command arguments it works as expected.

**Comment by niander** [comment]
It seems the change will only be introduced to [pip 20.3](https://github.com/pypa/pip/issues/8936). So I am closing this for now sine that fix should probably fix this.

**Comment by basnijholt** [comment]
Has this ever been addressed?

**Comment by niander** [comment]
@basnijholt I am not sure if it got fixed as I stopped using `--extra-index-url` and also stopped putting that inside an requirements.txt file. Are you having this problem as well?
