### ISSUE TITLE
Version 0.3.0 requires an unlisted and undocumented dependency

### ISSUE THREAD

**Issue by coordt** [microsoft/artifacts-keyring#33]
You used to be able to `pip install artifacts-keyring` it will install successfully and work.

Now it will install successfully and fail at runtime saying that `dotnet` isn't available.

There are no documentation changes on how to install it. Looking around, I wonder if I need to manually download and install the entire .Net core runtime just to be able to authenticate with Azure's package repository.

**Comment by look234** [comment]
Ran into this issue as well yesterday. Downgrading the package to `0.2.10`, `pip install artifacts-keyring==0.2.10`, seems to have got us back up and running for now.

**Comment by rgammans** [comment]
Could you link to the actual issue in the dev community, so other can follow the discussion
