### ISSUE TITLE
Install packages with Poetry and pyproject.toml

### ISSUE THREAD

**Issue by lynochka** [microsoft/artifacts-keyring#37]
Hei, could you please add to the readme how to use the package to add private packages to poetry evironment via pyproject.toml [[tool.poetry.source]] ).

Given that there is no username/password or explicit certificates, this is not obvious thanks!

**Comment by lynochka** [comment]
The reason I am asking is because I could not make it work, would you like to have my steps?

**Comment by Darsstar** [comment]
The last couple of days I have been leaving a paper trail on issues I looked at while trying to make things work.

Besides installing artifacts-keyring you might want to install azure-devops-artifacts-helpers which provides a virtualenv seeder called azdo-pip that installs artifacts-keyring into new virtual environments. You can configure virtualenv to use that seeder via the config file or setting the VIRTUALENV_SEEDER environment value to azdo-pip.

Poetry does not currently use keyring the same way that pip and pipenv do: python-poetry/poetry#4086.

Hopefully someone finds this helpfull.

**Comment by lynochka** [comment]
Hei, I did not see the link to the specific issue in the 'Developer Community', please share

**Comment by Darsstar** [comment]
https://developercommunity.visualstudio.com/t/Artifact-Feed--Connect-to-feed--Pip-/1429453
