### ISSUE TITLE
Support for Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by evakkuri** [microsoft/artifacts-keyring#44]
According to [this page](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops#connect-to-feed), "artifacts-keyring is not supported on newer versions of Ubuntu". This seems to mean that Ubuntu 18.04 LTS is not supported. This is a shame, as many Azure services such as Azure Machine Learning compute instances use this as their distribution of choice.

Any plans to update this package to support Ubuntu 18.04 LTS? Or should this service work in that version?

**Comment by shadargee1982** [comment]
Our engineers were able to get the artifacts-keyring working on Ubuntu 18.04.  Some tips:
* Make sure to have SDK set up. 
* Make sure to upgrade pip and setuptools to latest version. 
* Download the artifacts-keyring using the instructions in Connect to Feed (in the Artifacts UI).
* Then also update keyrings.alt package (e.g, `pip3 install -U keyrings.alt`). 
* You may need to do the interactive flow once.
