### ISSUE TITLE
Can we remove the dependency on dotnet SDK?

### ISSUE THREAD

**Issue by aatkinson** [microsoft/artifacts-keyring#53]
This package depends on [dotnet-sdk](https://pypi.org/project/artifacts-keyring/) but installation of [dotnet on Linux](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) can be finnicky. 

Various users of mine have had difficulty installing the dotnet requirement and I want to make it as easy as possible for them to authenticate with, and consume from, my [ADO Python feed](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-cli?view=azure-devops#consume-python-packages). It is also a requirement of Docker images my package consumers are using (bloat) - or is difficult to install in running Docker containers.

See [this item from Visual Studio develop community](https://developercommunity.visualstudio.com/t/Make-Python-installation-from-Azure-Devo/10175052?entry=suggestion&space=21&preview2=true) for details of my use case.

Why does this package have a dependency on dotnet-sdk, and what'd be involved to remove this dependency?

**Comment by noiano** [comment]
I had to manually modify the code of the package to make it work with just the .net runtime

**Comment by dekiesel** [comment]
Great that this PR got merged! 0.3.5 isn't available as of yet though. Any idea when it will be released?

Or is the wait due to [the PR that uses azure identity instead](https://github.com/microsoft/artifacts-keyring/pull/56)?

**Comment by embetten** [comment]
just released the 0.3.5 version!

**Comment by embetten** [comment]
closing please reopen if version [0.3.5](https://pypi.org/project/artifacts-keyring/0.3.5/) or later do not fix the issue. We have plans for future work to remove the runtime requirement as well
