### ISSUE TITLE
Please Push the newest version 0.3.3 to the pypi repository

### ISSUE THREAD

**Issue by suryadev99** [microsoft/artifacts-keyring#58]
We have two security updates that needs to be merged 
985455-DotNet (Nuget) Security Update for Newtonsoft.Json (GHSA-5crp-9r3c-p9vr)
988976-DotNet (Nuget) Security Update for NuGet.CommandLine (GHSA-g3q9-xf95-8hp5)

**Comment by austindonnelly** [comment]
Yes please - I need these security updated too.

**Comment by JohnSchmeichel** [comment]
0.3.3 has been published: https://pypi.org/project/artifacts-keyring/0.3.3/
