### ISSUE TITLE
Is it possible to use artifacts-keyring with a Service Principal?

### ISSUE THREAD

**Issue by NathanielMcVicar** [microsoft/artifacts-keyring#60]
I'm trying to publish wheels to a DevOps Artifact feed from a GitHub action with `twine`. I have a Service Principal with access, based on the steps in https://github.com/MicrosoftDocs/azure-devops-docs/issues/8141#issuecomment-1548825563, but in the past we've always used PATs with artifacts-keyring (typically through `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`). You can't create a PAT for a Service Principal, so I'm trying to determine if there is any alternative available. Thanks!

**Comment by John-Donalson** [comment]
in trying this too. i also use vss extensions endpoints. so far that thread doesnt work on my end even with the SP setup, azure artifacts does not even accept the command. 

so at this point we are still using a PAT

**Comment by John-Donalson** [comment]
> We don't have specific support for SP/MI in artifacts-keyring (or artifacts-credprovider which it uses behind the scenes) at this time, but if you can get an AAD access token (e.g. from `az account get-access-token`), that should work as the password with an arbitrary username, in the same way a PAT would

so theoretically something like this? 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AAD Access Token
      id: get_aad_token
      run: |
        echo "::set-output name=token::$(az account get-access-token --query accessToken -o tsv)"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Config NuGet to use Azure Artifacts
      env:
        TOKEN: ${{ steps.get_aad_token.outputs.token }}
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/<YourOrganization>/<YourProject>/_packaging/<YourFeed>/nuget/v3/index.json -n azure -u azuresdk -p $TOKEN --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore

**Comment by jmyersmsft** [comment]
I'm not really familiar with GH Actions, but that looks like it should work. You might consider setting up the environment variables to use with artifacts-credprovider rather than using `dotnet nuget add source`. Doing so would avoid persisting the token on disk, and some systems log command lines.

**Comment by NathanielMcVicar** [comment]
This worked great, I really appreciate the advice! However, I wonder is there any plan to set up some way to use OIDC or SPs directly with artifacts-credprovider, so we don't have to generate an intermediate bearer token? This seems like it would be a great feature, but I don't know how feasible it would be.

**Comment by John-Donalson** [comment]
This would be great and seeing as github is part of microsoft it would be extremely helpful and secure; so We just have to let them know how desired this is… imo it would be a great feature for those who do not want to migrate legacy artifact feeds…

**Comment by Laleee** [comment]
Hello @jmyersmsft,

Do you have any plans of supporting the SPA?

We want to run deployments from our on premise machines and this is causing a lot more issues than we could imagine.

**Comment by embetten** [comment]
As @jmyersmsft mentioned, the keyring runs the artifacts-credprovider behind the scenes. There is an issue on that repo tracking this enhancement [here](https://github.com/microsoft/artifacts-credprovider/issues/437).

**Comment by novablinkicelance** [comment]
All right. I suffered enough through this that I thought to post my solution here in case anybody in the future struggles like I did. For context, I'm using Azure ML Pipelines and authenticating to Azure DevOps using a managed identity. The assumption is that you can authenticate with the managed identity using the `az login --identity --username $DEFAULT_IDENTITY_CLIENT_ID` command. Here's how you can get a package using pip (adding previous steps in case you need them):

```
echo "Creating and activating Python virtual environment"
# This is not required but a good practice
python -m venv my-env
source my-env/bin/activate
# You can use Azure CLI
echo "Installing Azure CLI"
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
echo "Logging in to Azure CLI"
az login --identity --username $DEFAULT_IDENTITY_CLIENT_ID
echo "Getting token"
TOKEN=$(az account get-access-token --query accessToken -o tsv)
echo "Install packages"
pip install <package> --index-url "https://$TOKEN@<Organization>.pkgs.visualstudio.com/<Project>/_packaging/<Feed>/pypi/simple/"
```

This is how you can install Python packages from Azure Artifacts until artifacts-keyring supports non-interactive authentication with managed identities. Your managed identity will need Reader permissions on Azure DevOps.

Thanks @John-Donalson! Your solution helped me get mine.

**Comment by jmyersmsft** [comment]
Thanks for sharing that, @novablinkicelance! I would make two minor suggestions:

* Add a username (exact value doesn't matter) to the URL so that the token is the password. Systems are more likely to log usernames from Basic auth than passwords and as written, the token is the username. E.g.: `https://token:$TOKEN@<org>.pkgs...`. To be clear, Azure Artifacts does not log the username, but software or devices on your machine or network theoretically might.
* Use the `PIP_INDEX_URL` environment variable instead of the `--index-url` command line parameter. Some systems log process command lines.

**Comment by embetten** [comment]
[0.4.0](https://pypi.org/project/artifacts-keyring/0.4.0rc0/) now natively supports MI / SP set up instructions can be found on the https://github.com/microsoft/artifacts-credprovider/pull/492. Please let me know if you have and feedback or find any issues!

**Comment by embetten** [comment]
Thanks for the feed back - looks like we forgot pem certificates and this version is only supporting .pfx at the moment. We will look into fixing this.

**Comment by noiano** [comment]
Thank you @embetten ... are you also aware that current version of artifacts keyring is `0.4.0rc0` and this version is filtered out by some client like poetry ... they need a genuine stabile version like `0.4.0`

**Comment by noiano** [comment]
Hello @embetten I have to amend my previous comment ... I found a way to force poetry to use non stable version of artifacts-keyring by running

```bash
poetry self add artifacts-keyring==0.4.0rc0
```

Unfortunately it crashes without providing hints about what went wrong :(

**Comment by embetten** [comment]
Released a fix to support .pem with [0.4.0](https://pypi.org/project/artifacts-keyring/0.4.0/). 

Since 0.4.0 is a stable version supporting mi and service principals, I will close this issue. IF there are any further new issues with this new feature please create a new issue.

**Comment by brahimeg** [comment]
@embetten I'm trying to connect a compute instance in Azure ML that has a system-assigned identity with owner permissions on the feed, but I can't seem to get the managed identity authenticated. I keep encountering the "keyring skipped" error. My environment variable is set as follows:  

```
ARTIFACTS_CREDENTIALPROVIDER_FEED_ENDPOINTS='{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/*****/_packaging/*****/pypi/simple/", "clientId": "system"}]}'
```
