### ISSUE TITLE
artifacts-keyring succesfully installs with pip when dotnet dependency is missing.

### ISSUE THREAD

**Issue by olsgaard** [microsoft/artifacts-keyring#64]
dotnet is not an obvious dependency of artifacts-keyring.

As a developer on Azure, you will be met with instructions on portal.azure.com and dev.azure.com to `pip install keyring artifacts-keyring` in order to access feeds in Azure Artifacts.

The same goes for many guides posted by Microsoft and throughout documentation. Dotnet is a pretty substantial dependency and while this package can't be responsible for how the rest of Microsoft advertises its usage, it should fail early, at install time, when dependencies are not met.

Running `pip install keyring artifacts-keyring` should either install all dependencies or fail, with an error message that is understandable to most Python developers.

As of now, artifacts-keyring will successfully install without installing all dependencies. If necessary dependencies cannot be resolved by pip nor setup.py, I think it is best that the package fails to install.

**Comment by zooba** [comment]
Failing at install time isn't really possible, but it hopefully fails with a clear message as soon as you actually try to use it. If not, then it should.
