### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'

### ISSUE THREAD

**Issue by mharris4-eqr** [microsoft/artifacts-keyring#68]
I am receiving error the following error when trying to connect to our Azure Artifacts instance via pip while behind my corporate firewall. I know that we use decryption in our firewalls and we need to trust our internal CA authority for connectivity. Is there a solution for that in either this package or Credential provider? 

I am using python 3.10.11 and pip version 23.3.1 on Windows 10 21H2
Error - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'

I receive the error when using either of the following commands

 pip install azure-mgmt-search==9.1.0 --use-feature=truststore
 pip install azure-mgmt-search==9.1.0

**Comment by highviolet** [comment]
We're seeing the same issue. @mharris4-eqr : Did you find any solution to this?

**Comment by mharris4-eqr** [comment]
My issue was twofold -
1. We were using an older version of pip that wouldn’t use the system store
on windows. But to update pip we had to use pip so we had to update pip
config to point at our internal pki cert then update pip

2. Once pip was updated and artifacts-keyring was installed I had to update
cacerts.pem to include my pki certs for it to work

*Monty Harris*

*Cloud Architect*

815.252.6858

Equity Residential

Two N. Riverside Plaza, Suite 400

Chicago, IL 60606

EquityResidential.com  -  live remarkably

<https://www.linkedin.com/company/equity-residential>
<https://www.facebook.com/equityapartments/?ref=page_internal>
<https://www.glassdoor.com/Overview/Working-at-Equity-Residential-EI_IE3635.11,29.htm>
<https://www.instagram.com/eqrcareers/?hl=en>
<https://twitter.com/EquityRes>
