### ISSUE TITLE
Update artifacts-credprovider to v1.2.2

### ISSUE THREAD

**Issue by kitshinghk-crypto** [microsoft/artifacts-keyring#78]
Hi,

artifacts-credprovider has released v1.2.2 recently. It would be nice that artifacts-keyring update the use of artifacts-credprovider to v1.2.2, which include updates on Microsoft.Identity.Client.

**Comment by embetten** [comment]
1.2.3 is released with keyring [0.4.0](https://pypi.org/project/artifacts-keyring/0.4.0/)
